# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlassian-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "683a03bc0b1442da18b2eab01c89d1eb85bbd9b7cc285ac29fb3be5aebc0274b"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1038e18ca6e601720714379e786aa81db06531412ec6e74f82f25402927b4653"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6605d5a9182015ad578e5d70e4db619f4866f0b4dbb08a290e406486093cb6eb"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00023fe69adbcda495b5f5a2110804f8efa5ea004e759f4fff752233f9c2b105"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_linux_arm64.tar.gz"
    end
  end

  name "atlassian-cli"
  desc "Command-line tool for Atlassian Cloud — Jira, Confluence, JPD, Compass"
  homepage "https://github.com/Well-Polaris/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlassian-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlassian"]
    end
  end

  # No zap stanza required

end
