# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlassian-cli" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "f9d8f7239ea703e9fbede94c8d4d3671bcee9f0b0b748ca0557f604044bef517"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d252f0c86ea346a499935603986fd51d111d51dff81afb1e4349bead22df3a5f"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1c66d62131d87a1d282a42d57151b995d43b6665334556a2d1700c9a894108dd"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d0e8821bb347d49373c24c719151255ad91724312d8520104ddb887443bb23a"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_linux_arm64.tar.gz"
    end
  end

  name "atlassian-cli"
  desc "Command-line tool for Atlassian Cloud — Jira, Confluence, JPD, Compass"
  homepage "https://github.com/Well-Polaris/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlassian"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlassian"]
    end
  end

  # No zap stanza required

end
