# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlassian-cli" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "6020213c9c6c25b83bd344e1319ed4473bf488f0138666ca6e1207c84bd8e9cb"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "44ca5ec008dd91816b7a7262f35edef7de3751bd29a8c8e1ada978aef6ebefda"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "28b977c048885555160c08f92aaa6ce63346542838901def9d71524f77bbe88c"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "697f0644958dde491382009adf216d8ec16e6304779a9c46c48a3975cd83c8ba"
      url "https://github.com/Well-Polaris/atlassian-cli/releases/download/v#{version}/atlassian-cli_linux_arm64.tar.gz"
    end
  end

  name "atlassian-cli"
  desc "Command-line tool for Atlassian Cloud — Jira, Confluence, JPD, Compass"
  homepage "https://github.com/Well-Polaris/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlassian-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlassian"]
    end
  end

  # No zap stanza required

end
